name: Push Release to PyPi (pydoover)

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'I want to manually trigger a PyPi push, without publishing a GitHub release (not recommended!)'
        required: true
        type: boolean
  release:
    types: [ created ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pydoover

    if: github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' &&  github.event.inputs.confirmation != 'false')
    steps:
      - uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.11
      - name: Build Package
        run: uv build
      - name: Publish Package
        run: uv publish
